search_space:
  learning_rate:
    _type: choice
    _value: [1e-4,3e-4, 1e-3,5e-4]
  head_dropout:
    _type: choice
    _value: [0.1, 0.2, 0.3, 0.4, 0.5]
  attention_dropout:
    _type: choice
    _value: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  plateau_patience:
    _type: choice
    _value: [3, 5,8, 10]
  plateau_factor:
    _type: choice
    _value: [0.5,0.7, 0.8, 0.9, 0.95]
  early_stop_patience:
    _type: choice
    _value: [5, 10, 15, 20]
  
  
trial_command: python fusion_train.py
trial_code_directory: ../

trial_concurrency: 1
max_trial_number: 10

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
